package entity;

import main.GamePanel;

import java.awt.*;

// The Particle class represents a small particle that is generated by an entity.
// It has properties like color, size, speed, direction, and lifespan, and it moves over time.
public class Particle extends Entity {

    Entity generator;  // The entity that generated this particle.
    Color color;      // The color of the particle.
    int size;         // The size of the particle.
    int xd;           // The horizontal direction of the particle's movement.
    int yd;           // The vertical direction of the particle's movement.

    // Constructor to initialize the particle's properties such as color, size, speed, direction, and lifespan.
    public Particle(GamePanel gp, Entity generator, Color color, int size, int speed, int maxLife, int xd, int yd) {
        super(gp);  // Call the superclass constructor.

        // Initialize the particle's properties.
        this.generator = generator;
        this.color = color;
        this.size = size;
        this.speed = speed;
        this.maxLife = maxLife;
        this.xd = xd;
        this.yd = yd;

        life = maxLife;  // Set the particle's initial life to its maximum life.

        // Calculate the initial position of the particle, centered relative to the generator's position.
        int offset = (gp.tileSize / 2) - (size / 2);
        worldX = generator.worldX + offset;
        worldY = generator.worldY + offset;
    }

    // Update the particle's position and state over time.
    public void update() {
        life--;  // Decrease the particle's life by 1.

        // Apply gravity to the particle when its life is below a third of its max life.
        if (life < maxLife / 3) {
            yd++;  // Increase vertical speed (falling down).
        }

        // Move the particle based on its direction (xd, yd) and speed.
        worldX += xd * speed;
        worldY += yd * speed;

        // If the particle's life reaches 0, set it to be inactive.
        if (life == 0) {
            alive = false;
        }
    }

    // Draw the particle on the screen.
    public void draw(Graphics2D g2) {
        // Calculate the position of the particle on the screen relative to the player's position.
        int screenX = worldX - gp.player.worldX + gp.player.screenX;
        int screenY = worldY - gp.player.worldY + gp.player.screenY;

        // Set the color for the particle and fill a rectangle at the calculated screen position.
        g2.setColor(color);
        g2.fillRect(screenX, screenY, size, size);  // Draw the particle as a filled square.
    }
}